// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: api/wallet/v1/wallet.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Wallet_CreateWalletByMnemonic_FullMethodName   = "/wallet.v1.Wallet/CreateWalletByMnemonic"
	Wallet_GetWalletAddressByUserId_FullMethodName = "/wallet.v1.Wallet/GetWalletAddressByUserId"
	Wallet_Transfer2WalletAddress_FullMethodName   = "/wallet.v1.Wallet/Transfer2WalletAddress"
)

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletClient interface {
	CreateWalletByMnemonic(ctx context.Context, in *CreateWalletByMnemonicRequest, opts ...grpc.CallOption) (*CreateWalletByMnemonicResponse, error)
	GetWalletAddressByUserId(ctx context.Context, in *GetWalletAddressByUserIdRequest, opts ...grpc.CallOption) (*GetWalletAddressByUserIdResponse, error)
	Transfer2WalletAddress(ctx context.Context, in *Transfer2WalletAddressRequest, opts ...grpc.CallOption) (*Transfer2WalletAddressResponse, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) CreateWalletByMnemonic(ctx context.Context, in *CreateWalletByMnemonicRequest, opts ...grpc.CallOption) (*CreateWalletByMnemonicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWalletByMnemonicResponse)
	err := c.cc.Invoke(ctx, Wallet_CreateWalletByMnemonic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetWalletAddressByUserId(ctx context.Context, in *GetWalletAddressByUserIdRequest, opts ...grpc.CallOption) (*GetWalletAddressByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletAddressByUserIdResponse)
	err := c.cc.Invoke(ctx, Wallet_GetWalletAddressByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) Transfer2WalletAddress(ctx context.Context, in *Transfer2WalletAddressRequest, opts ...grpc.CallOption) (*Transfer2WalletAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transfer2WalletAddressResponse)
	err := c.cc.Invoke(ctx, Wallet_Transfer2WalletAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
// All implementations must embed UnimplementedWalletServer
// for forward compatibility.
type WalletServer interface {
	CreateWalletByMnemonic(context.Context, *CreateWalletByMnemonicRequest) (*CreateWalletByMnemonicResponse, error)
	GetWalletAddressByUserId(context.Context, *GetWalletAddressByUserIdRequest) (*GetWalletAddressByUserIdResponse, error)
	Transfer2WalletAddress(context.Context, *Transfer2WalletAddressRequest) (*Transfer2WalletAddressResponse, error)
	mustEmbedUnimplementedWalletServer()
}

// UnimplementedWalletServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServer struct{}

func (UnimplementedWalletServer) CreateWalletByMnemonic(context.Context, *CreateWalletByMnemonicRequest) (*CreateWalletByMnemonicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWalletByMnemonic not implemented")
}
func (UnimplementedWalletServer) GetWalletAddressByUserId(context.Context, *GetWalletAddressByUserIdRequest) (*GetWalletAddressByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletAddressByUserId not implemented")
}
func (UnimplementedWalletServer) Transfer2WalletAddress(context.Context, *Transfer2WalletAddressRequest) (*Transfer2WalletAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer2WalletAddress not implemented")
}
func (UnimplementedWalletServer) mustEmbedUnimplementedWalletServer() {}
func (UnimplementedWalletServer) testEmbeddedByValue()                {}

// UnsafeWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServer will
// result in compilation errors.
type UnsafeWalletServer interface {
	mustEmbedUnimplementedWalletServer()
}

func RegisterWalletServer(s grpc.ServiceRegistrar, srv WalletServer) {
	// If the following call pancis, it indicates UnimplementedWalletServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Wallet_ServiceDesc, srv)
}

func _Wallet_CreateWalletByMnemonic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletByMnemonicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).CreateWalletByMnemonic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_CreateWalletByMnemonic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).CreateWalletByMnemonic(ctx, req.(*CreateWalletByMnemonicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetWalletAddressByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletAddressByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetWalletAddressByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_GetWalletAddressByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetWalletAddressByUserId(ctx, req.(*GetWalletAddressByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_Transfer2WalletAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transfer2WalletAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Transfer2WalletAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_Transfer2WalletAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Transfer2WalletAddress(ctx, req.(*Transfer2WalletAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wallet_ServiceDesc is the grpc.ServiceDesc for Wallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.v1.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWalletByMnemonic",
			Handler:    _Wallet_CreateWalletByMnemonic_Handler,
		},
		{
			MethodName: "GetWalletAddressByUserId",
			Handler:    _Wallet_GetWalletAddressByUserId_Handler,
		},
		{
			MethodName: "Transfer2WalletAddress",
			Handler:    _Wallet_Transfer2WalletAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/wallet/v1/wallet.proto",
}
