server:
  name:  solana_aggregate
  env: develop
  http:
    addr: 0.0.0.0:8015
    timeout: 100s
  grpc:
    addr: 0.0.0.0:9915
    timeout: 100s
  sol_endpoint:
    endpoint: "https://api.devnet.solana.com"
data:
  database:
    driver: mysql
    user: root
    protocol: tcp
    database: test